### ISSUE TITLE
binary_operator `<>` is not consistent with other operators

### ISSUE THREAD

**Issue by wkirschbaum** [elixir-lang/tree-sitter-elixir#45]
in effort to build indentation using tree-sitter i ran into the following issue

with the following code outputs the desired structure
```
    1 +
      2 +
      3 +
      4
```
with output ( value in [] )
```
(binary_operator
    left: 
     (binary_operator
      left: (binary_operator left: (integer [1] ) operator: + right: (integer [2] ))
      operator: + right: (integer [3]))
    operator: + right: (integer [4]))
  ```
  
 but with the following structure
 
 ```
    "1" <>
      "2" <>
        "3" <>
          "4"
 ```
 
 with output ( value in [] )
 
 ```
(binary_operator
    left: (string quoted_end: " (quoted_content ["1"]) ")
    operator: <>
    right: 
     (binary_operator
      left: (string quoted_end: " (quoted_content ["2"]) ")
      operator: <>
      right: 
       (binary_operator
        left: (string quoted_end: " (quoted_conten ["3"]t) ")
        operator: <>
        right: (string quoted_end: " (quoted_content ["4"]) "))))
 ```

The left and right operators are swapped when using `<>` which make it hard to consistently parse and indent the two examples the same way.
